#+TITLE: Git basics

* git internals: commits, trees & blobs.

git cat-file -p b1314d99959cfb31b46cfb3ff6b61ed69eba11b1 => commit
git cat-file -p 05755f45e56b77595d8d28668402d674d6c97d8b => tree
git cat-file -p 65c99f780903e84a066531281c72640242025cfb => blob

let's commit this.

we get:

** exercice 1:
what is the content of secret.txt?
git cat-file -p ad12e281e300fdb4fcffad5260579803f0064e0c

** history
cat .git/HEAD
cat .git/refs/heads/master

history is a linked list of commits that each reference a tree.

* everyday commands
** init & clone
git init
=> create a new repo
git clone git@github.com:besport/git-course
** inspection
git status
=> shows you the state of the repository
git branch
=> shows you local branches
git branch -a
=> shows you all branches
*** log
git log
=> list of commits
git log --stat
=> list of commits with file modification statistics
git log --patch
=> list of commits with patches
*** git diff
git diff --stat branch
=> shows file stats to from current tree to branch
git diff branch
=> shows patch between current tree & branch
git diff branch_1..branch_2
git diff HEAD^..branch_2
git diff branch_x..a1234
=> diff between different git revisions which can be HEAD (relative to current tree history), <commit hash>, branch name, tag name.
**** exercice 2
how many lines is the diff between commit 35c81 and branch_1?
** checkout
git checkout <exisiting-branch-name>
=> checks out tree corresponding to that branch
git checkout -b <new-branch>
=> creates new branch starting from current tree
** staging
staging: it's a temporary space in which you prepare your commit
git add <file>
=> adds all modifications of file to staging.
git add --interactive
=> choose individual hunks (patches) to commit
git reset
=> removes everything from staging
** committing
git commit
=> commits the current staging with $EDITOR for commit message.
git commit -m "[doc] explain everything"
=> commits the current staging to a commit with -m message
git commit -a -m "[doc] explain commits"
=> this creates a new commit after adding all modifications to staging
see: [[https://github.com/besport/bs/wiki/Coding-style][bs coding style/commit format]]
* remotes
remote add github git@github.com:besport/git-course.git
* rebasing
* cherry picking
* -
